title: Mobarok Miyazi
markdown: kramdown
url: ""
baseurl: ""

# for atom feed
author:
  name: Mobarok
  email: moba@gmail.com
  image: "https://avatars.githubusercontent.com/u/66001685?v=4"
  bio: I'm <b>Mobarok Miyazi</b>, from Bangladesh. I'm a computer programmer. this my blog site. I like to share different things to the world.
  github: "mobaarok"
  instagram: "https://www.instagram.com/mobarok_miyazi/"

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate-v2

defaults:
  - scope:
      path: ""
    values:
      layout: "post"
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:categories/:year/:month/:day/:title/

# Pagination Settings
pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true